"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var IUnitedStatesState;
(function (IUnitedStatesState) {
    IUnitedStatesState["AL"] = "AL";
    IUnitedStatesState["AK"] = "AK";
    IUnitedStatesState["AZ"] = "AZ";
    IUnitedStatesState["AR"] = "AR";
    IUnitedStatesState["CA"] = "CA";
    IUnitedStatesState["CO"] = "CO";
    IUnitedStatesState["CT"] = "CT";
    IUnitedStatesState["DE"] = "DE";
    IUnitedStatesState["FL"] = "FL";
    IUnitedStatesState["GA"] = "GA";
    IUnitedStatesState["HI"] = "HI";
    IUnitedStatesState["ID"] = "ID";
    IUnitedStatesState["IL"] = "IL";
    IUnitedStatesState["IN"] = "IN";
    IUnitedStatesState["IA"] = "IA";
    IUnitedStatesState["KS"] = "KS";
    IUnitedStatesState["KY"] = "KY";
    IUnitedStatesState["LA"] = "LA";
    IUnitedStatesState["ME"] = "ME";
    IUnitedStatesState["MD"] = "MD";
    IUnitedStatesState["MA"] = "MA";
    IUnitedStatesState["MI"] = "MI";
    IUnitedStatesState["MN"] = "MN";
    IUnitedStatesState["MS"] = "MS";
    IUnitedStatesState["MO"] = "MO";
    IUnitedStatesState["MT"] = "MT";
    IUnitedStatesState["NE"] = "NE";
    IUnitedStatesState["NV"] = "NV";
    IUnitedStatesState["NH"] = "NH";
    IUnitedStatesState["NJ"] = "NJ";
    IUnitedStatesState["NM"] = "NM";
    IUnitedStatesState["NY"] = "NY";
    IUnitedStatesState["NC"] = "NC";
    IUnitedStatesState["ND"] = "ND";
    IUnitedStatesState["OH"] = "OH";
    IUnitedStatesState["OK"] = "OK";
    IUnitedStatesState["OR"] = "OR";
    IUnitedStatesState["PA"] = "PA";
    IUnitedStatesState["RI"] = "RI";
    IUnitedStatesState["SC"] = "SC";
    IUnitedStatesState["SD"] = "SD";
    IUnitedStatesState["TN"] = "TN";
    IUnitedStatesState["TX"] = "TX";
    IUnitedStatesState["UT"] = "UT";
    IUnitedStatesState["VT"] = "VT";
    IUnitedStatesState["VA"] = "VA";
    IUnitedStatesState["WA"] = "WA";
    IUnitedStatesState["WV"] = "WV";
    IUnitedStatesState["WI"] = "WI";
    IUnitedStatesState["WY"] = "WY";
})(IUnitedStatesState = exports.IUnitedStatesState || (exports.IUnitedStatesState = {}));
//# sourceMappingURL=unitedStatesState.js.map